#!/usr/bin/env python3
"""
Track-Before-Detect (TBD) Brute-Force Algorithm — Interview Problem
=====================================================================

BACKGROUND:
-----------
Track-Before-Detect is used in space domain awareness to find extremely
faint objects moving through a sequence of images. The object is too dim
to detect in any single frame (sub-detection-threshold SNR), but by
coherently integrating pixel values along candidate trajectories across
multiple frames, the signal accumulates as O(N) while noise grows as
O(sqrt(N)), enabling detection.

THE ALGORITHM (Brute-Force Shift-and-Stack):
--------------------------------------------
For each candidate starting position (x0, y0) and velocity (vx, vy):
    1. Predict the object position in each frame t:
           px = round(x0 + vx * t)
           py = round(y0 + vy * t)
    2. Sum the pixel values at those positions across all frames:
           T(x0, y0, vx, vy) = sum_{t=0}^{N-1} frame[t, py, px]
    3. The trajectory with the highest test statistic T is the detection.

Boundary handling: if any predicted position falls outside the image,
that trajectory is invalid and skipped.

YOUR TASK:
----------
1. Port this brute-force algorithm to CUDA/C++.
2. Read the binary data files generated by this script.
3. Produce identical detection results.
4. Report wall-clock time for the search phase.
5. Aim for maximum GPU utilization and memory efficiency.

DELIVERABLES:
    - A CUDA/C++ source file that compiles and runs
    - Detected (x0, y0, vx, vy) matching the reference output
    - Performance measurements (kernel time, total time, speedup)

EVALUATION CRITERIA:
    - Correctness (matching detected trajectory)
    - Speedup over Python baseline
    - Parallelization strategy and memory access patterns
    - Code clarity and engineering quality

DATA FORMAT:
    tbd_frames.bin:
        Header: 3 x int32 (nx, ny, n_frames)
        Data:   n_frames x ny x nx float32 values (row-major, frame-major)
    
    tbd_params.bin:
        3 x float32 (v_min, v_max, v_step)

RUN THIS SCRIPT FIRST to generate the data files, then implement your
CUDA solution to process them.
"""

import numpy as np
import time
import struct
import os
import sys

# ============================================================
# PROBLEM PARAMETERS (Target)
# ============================================================
# NX, NY = 3072, 3072           # Image dimensions (pixels)
# N_FRAMES = 300               # Number of temporal frames
# BG_MEAN = 100.0             # Background Poisson rate (photons/pixel/frame)
# OBJ_SIGNAL = 25.0           # Object signal added per frame (photons)
#                              # Per-frame SNR ~ OBJ_SIGNAL / sqrt(BG_MEAN)
#                              # Stacked SNR  ~ per_frame_SNR * sqrt(N_FRAMES)

# ============================================================
# PROBLEM PARAMETERS (Benchmarking)
# ============================================================
NX, NY = 1024, 1024           # Image dimensions (pixels)
N_FRAMES = 300               # Number of temporal frames
BG_MEAN = 100.0             # Background Poisson rate (photons/pixel/frame)
OBJ_SIGNAL = 35.0           # Object signal added per frame (photons)
                             # Per-frame SNR ~ OBJ_SIGNAL / sqrt(BG_MEAN)
                             # Stacked SNR  ~ per_frame_SNR * sqrt(N_FRAMES)

# Ground truth trajectory — auto-computed from current parameters (see below)

# Velocity search grid
# V_HYP = 155               # Corresponds to 24025 velocity hypothesis
V_HYP = 50
V_MIN  = -3.0               # Min velocity (pixels/frame)
V_MAX  =  3.0               # Max velocity (pixels/frame)
V_STEP = (V_MAX - V_MIN) / (V_HYP - 1)  # Velocity step size
SEED   = 42                 # RNG seed for reproducibility
NUMPY_COMPUTE = False        # Run NumPy vectorized reference search (set False to skip)
VX_VY_RATIO   = 2.0         # Desired ratio of vx / |vy| for the ground truth trajectory


# ============================================================
# GROUND TRUTH (auto-computed to be valid for current params)
# ============================================================
def compute_ground_truth():
    """
    Pick a ground truth trajectory that:
      - keeps the object inside [0, NX-1] x [0, NY-1] for all N_FRAMES
      - uses a fixed 0.25 px/frame grid so values are always clean round numbers,
        independent of V_HYP
    Starting position is centered in the valid range.
    """
    GT_STEP = V_STEP
    velocities = np.arange(V_MIN, V_MAX + GT_STEP / 2, GT_STEP)

    def valid_start_range(v, n_frames, n_pixels):
        """Return (lo, hi) of valid starting indices for velocity v."""
        end_disp = int(round(v * (n_frames - 1)))
        return (0, n_pixels - 1 - end_disp) if v >= 0 else (-end_disp, n_pixels - 1)

    valid_vx = [v for v in velocities
                if valid_start_range(v, N_FRAMES, NX)[0] <= valid_start_range(v, N_FRAMES, NX)[1]]
    valid_vy = [v for v in velocities
                if valid_start_range(v, N_FRAMES, NY)[0] <= valid_start_range(v, N_FRAMES, NY)[1]]

    def pick_v(candidates, positive, target_mag):
        """Pick the valid non-zero velocity whose magnitude is closest to target_mag."""
        nonzero = [v for v in candidates if (v > 0 if positive else v < 0)]
        if not nonzero:
            return 0.0
        return float(min(nonzero, key=lambda v: abs(abs(v) - target_mag)))

    # Choose base magnitude so the trajectory uses ~1/3 of the image in each axis,
    # then scale vx and vy according to VX_VY_RATIO so they are never equal.
    max_vx_mag = max((abs(v) for v in valid_vx if v != 0), default=0.0)
    max_vy_mag = max((abs(v) for v in valid_vy if v != 0), default=0.0)
    base_mag = min(max_vx_mag, max_vy_mag) / 3
    # vx_target / vy_target = VX_VY_RATIO  →  vx_target = ratio * vy_target
    # keep geometric mean equal to base_mag: sqrt(vx_target * vy_target) = base_mag
    vy_target = base_mag / (VX_VY_RATIO ** 0.5)
    vx_target = VX_VY_RATIO * vy_target

    vx = pick_v(valid_vx, positive=True,  target_mag=vx_target)
    vy = pick_v(valid_vy, positive=False, target_mag=vy_target)

    lox, hix = valid_start_range(vx, N_FRAMES, NX)
    loy, hiy = valid_start_range(vy, N_FRAMES, NY)
    x0 = float((lox + hix) // 2)
    y0 = float((loy + hiy) // 2)
    return x0, y0, vx, vy


TRUE_X0, TRUE_Y0, TRUE_VX, TRUE_VY = compute_ground_truth()


# ============================================================
# DATA GENERATION
# ============================================================
def generate_data():
    """Generate synthetic frames with Poisson background + faint moving object."""
    rng = np.random.default_rng(SEED)
    frames = np.zeros((N_FRAMES, NY, NX), dtype=np.float32)

    for t in range(N_FRAMES):
        # Poisson background
        frames[t] = rng.poisson(BG_MEAN, size=(NY, NX)).astype(np.float32)

        # Inject object signal at ground-truth trajectory position
        obj_x = int(round(TRUE_X0 + TRUE_VX * t))
        obj_y = int(round(TRUE_Y0 + TRUE_VY * t))
        if 0 <= obj_x < NX and 0 <= obj_y < NY:
            frames[t, obj_y, obj_x] += rng.poisson(OBJ_SIGNAL)

    return frames


def save_binary(frames, filename="tbd_frames.bin"):
    """Save frames as raw binary for C++ consumption."""
    with open(filename, "wb") as f:
        f.write(struct.pack("iii", NX, NY, N_FRAMES))
        f.write(frames.astype(np.float32).tobytes())
    print(f"  Saved {filename} ({os.path.getsize(filename):,} bytes)")


def save_params(filename="tbd_params.bin"):
    """Save velocity search parameters as raw binary."""
    with open(filename, "wb") as f:
        f.write(struct.pack("fff", V_MIN, V_MAX, V_STEP))
    print(f"  Saved {filename}")


# ============================================================
# BRUTE-FORCE TBD  (Pure Python — the algorithm to port)
# ============================================================
def brute_force_tbd(frames, max_rows=None):
    """
    Brute-force shift-and-stack search.

    For EVERY (x0, y0, vx, vy) combination, compute:
        T = sum_{t} frame[t, round(y0 + vy*t), round(x0 + vx*t)]
    Return the trajectory with the maximum T.

    Parameters
    ----------
    frames : ndarray, shape (N_FRAMES, NY, NX)
    max_rows : int or None
        If set, only search the first max_rows rows of y0 (for quick testing).
    """
    n_frames, ny, nx = frames.shape
    velocities = np.arange(V_MIN, V_MAX + V_STEP / 2, V_STEP).astype(np.float64)
    n_vel = len(velocities)
    search_ny = ny if max_rows is None else min(max_rows, ny)

    total_traj = nx * search_ny * n_vel * n_vel
    print(f"  Image size      : {nx} x {ny}")
    print(f"  Frames          : {n_frames}")
    print(f"  Velocity grid   : {n_vel} x {n_vel} = {n_vel*n_vel} hypotheses")
    print(f"  Search rows     : {search_ny} / {ny}")
    print(f"  Total trajectories : {total_traj:,}")
    print(f"  Total pixel reads  : {total_traj * n_frames:,}")
    print()

    best_stat = -1e30
    best_x0 = best_y0 = 0
    best_vx = best_vy = 0.0

    t_start = time.time()

    for iy0 in range(search_ny):
        if iy0 % 16 == 0:
            elapsed = time.time() - t_start
            pct = 100.0 * iy0 / search_ny
            eta = (elapsed * (search_ny - iy0) / iy0) if iy0 > 0 else 0
            print(f"\r  Row {iy0:4d}/{search_ny} "
                  f"({pct:5.1f}%)  elapsed {elapsed:7.1f}s  ETA {eta:7.0f}s",
                  end="", flush=True)

        for ix0 in range(nx):
            for vi in range(n_vel):
                vx = velocities[vi]
                for vj in range(n_vel):
                    vy = velocities[vj]

                    # --- Shift-and-stack along this trajectory ---
                    stat = 0.0
                    valid = True
                    for t in range(n_frames):
                        px = int(round(ix0 + vx * t))
                        py = int(round(iy0 + vy * t))
                        if px < 0 or px >= nx or py < 0 or py >= ny:
                            valid = False
                            break
                        stat += frames[t, py, px]

                    if valid and stat > best_stat:
                        best_stat = stat
                        best_x0 = ix0
                        best_y0 = iy0
                        best_vx = vx
                        best_vy = vy

    elapsed = time.time() - t_start
    print()
    return best_x0, best_y0, best_vx, best_vy, best_stat, elapsed


# ============================================================
# NUMPY-VECTORIZED REFERENCE (fast, for generating ground truth)
# ============================================================
def vectorized_tbd(frames):
    """
    Vectorized shift-and-stack using NumPy.
    Still brute-force, but runs in minutes rather than hours.
    Used to generate the reference answer.
    """
    n_frames, ny, nx = frames.shape
    velocities = np.arange(V_MIN, V_MAX + V_STEP / 2, V_STEP).astype(np.float32)
    n_vel = len(velocities)
    time_steps = np.arange(n_frames, dtype=np.float32)

    best_stat = -1e30
    best_x0 = best_y0 = 0
    best_vx = best_vy = 0.0

    # Precompute all starting coordinates
    x0_grid = np.arange(nx, dtype=np.float32)
    y0_grid = np.arange(ny, dtype=np.float32)

    t_start = time.time()
    total = n_vel * n_vel
    done = 0

    for vi in range(n_vel):
        vx = velocities[vi]
        for vj in range(n_vel):
            vy = velocities[vj]
            done += 1
            if done % 50 == 0:
                elapsed = time.time() - t_start
                eta = elapsed * (total - done) / done if done > 0 else 0
                print(f"\r  Velocity {done}/{total} "
                      f"({100*done/total:.0f}%)  "
                      f"elapsed {elapsed:.1f}s  ETA {eta:.0f}s",
                      end="", flush=True)

            # For each frame, compute displaced coordinates for ALL (x0, y0)
            # x_coords[t] = x0 + vx*t  → shape (nx,) broadcast over frames
            # y_coords[t] = y0 + vy*t  → shape (ny,) broadcast over frames
            stat_map = np.zeros((ny, nx), dtype=np.float64)
            all_valid = np.ones((ny, nx), dtype=bool)

            for t in range(n_frames):
                px = np.round(x0_grid + vx * t).astype(np.int32)  # (nx,)
                py = np.round(y0_grid + vy * t).astype(np.int32)  # (ny,)

                # Masks for valid coordinates
                valid_x = (px >= 0) & (px < nx)   # (nx,)
                valid_y = (py >= 0) & (py < ny)   # (ny,)

                # 2D validity: outer product
                valid_2d = valid_y[:, None] & valid_x[None, :]  # (ny, nx)
                all_valid &= valid_2d

                # Clamp for safe indexing (invalid pixels get clamped, masked later)
                px_safe = np.clip(px, 0, nx - 1)
                py_safe = np.clip(py, 0, ny - 1)

                # Gather pixel values: frame[t, py_safe[y0], px_safe[x0]]
                stat_map += frames[t][np.ix_(py_safe, px_safe)]

            # Mask out invalid trajectories
            stat_map[~all_valid] = -1e30

            # Find maximum in this velocity slice
            idx = np.argmax(stat_map)
            iy, ix = np.unravel_index(idx, (ny, nx))
            s = stat_map[iy, ix]
            if s > best_stat:
                best_stat = s
                best_x0 = int(ix)
                best_y0 = int(iy)
                best_vx = float(vx)
                best_vy = float(vy)

    elapsed = time.time() - t_start
    print()
    return best_x0, best_y0, best_vx, best_vy, best_stat, elapsed


# ============================================================
# MAIN
# ============================================================
def main():
    print("=" * 64)
    print("  Track-Before-Detect: Brute-Force Shift-and-Stack")
    print("  Interview Problem — GPU Engineer Position")
    print("=" * 64)
    print()

    # --- Print ground truth before any computation ---
    per_snr   = OBJ_SIGNAL / np.sqrt(BG_MEAN)
    stack_snr = per_snr * np.sqrt(N_FRAMES)
    print("[0] Ground truth trajectory (auto-computed):")
    print(f"    x0={TRUE_X0}, y0={TRUE_Y0}, vx={TRUE_VX}, vy={TRUE_VY}")
    print(f"    Image       : {NX} x {NY},  frames: {N_FRAMES}")
    print(f"    Per-frame SNR : {per_snr:.2f}  (invisible by eye)")
    print(f"    Stacked SNR   : {stack_snr:.2f}  (over {N_FRAMES} frames)")
    print()

    # --- Generate data ---
    print("[1] Generating synthetic data...")
    frames = generate_data()
    save_binary(frames)
    save_params()
    print()

    # --- Always write ground truth to reference file ---
    with open("tbd_reference.txt", "w") as f:
        f.write(f"x0={TRUE_X0:.2f}\n")
        f.write(f"y0={TRUE_Y0:.2f}\n")
        f.write(f"vx={TRUE_VX:.2f}\n")
        f.write(f"vy={TRUE_VY:.2f}\n")
    print(f"  Saved tbd_reference.txt (ground truth)")
    print()

    # --- Compute reference answer (vectorized, fast) ---
    if NUMPY_COMPUTE:
        print("[2] Computing reference answer (NumPy vectorized)...")
        x0, y0, vx, vy, stat, elapsed = vectorized_tbd(frames)
        print()
        print(f"  REFERENCE RESULT:")
        print(f"    Detected : x0={x0}, y0={y0}, vx={vx:.2f}, vy={vy:.2f}")
        print(f"    Statistic: {stat:.1f}")
        print(f"    Time     : {elapsed:.2f} s")
        print(f"    Pos error: dx={x0 - TRUE_X0:.1f}, dy={y0 - TRUE_Y0:.1f}")
        print(f"    Vel error: dvx={vx - TRUE_VX:.2f}, dvy={vy - TRUE_VY:.2f}")

        with open("tbd_reference.txt", "a") as f:
            f.write(f"statistic={stat:.6f}\n")
        print(f"  Updated tbd_reference.txt (added statistic)")
        print()
    else:
        print("[2] Skipping NumPy vectorized search (NUMPY_COMPUTE = False)")

    # --- Optional: run the pure-Python brute-force on a small patch ---
    run_bruteforce = "--bruteforce" in sys.argv
    if run_bruteforce:
        n_test_rows = 8
        print(f"[3] Running pure-Python brute-force ({n_test_rows} rows for timing)...")
        _, _, _, _, _, bf_time = brute_force_tbd(frames, max_rows=n_test_rows)
        est_full = bf_time * (NY / n_test_rows)
        print(f"  Partial time : {bf_time:.1f} s ({n_test_rows} rows)")
        print(f"  Estimated full: {est_full:.0f} s ({est_full/60:.0f} min)")
    else:
        print("[3] Skipping pure-Python brute-force (add --bruteforce to run)")
        print("    Estimated time for full search: ~2-4 hours on a modern CPU")

    print()
    print("=" * 64)
    print("  Files generated. Implement your CUDA solution to process")
    print("  tbd_frames.bin and tbd_params.bin, and match the reference.")
    print("=" * 64)


if __name__ == "__main__":
    main()
